SELECT ERP_PRODUTO_SERVICO_CODIGOS.NR_LICENCA, ERP_PRODUTO_SERVICO_CODIGOS.ID_PRODUTO_SERVICO,
       ERP_PRODUTO_SERVICO_CODIGOS.ID_PRODUTOS_CODIGOS
FROM ERP_PRODUTO_SERVICO_CODIGOS
WHERE ERP_PRODUTO_SERVICO_CODIGOS.ID_PRODUTOS_CODIGOS LIKE '%''%';

# UPDATE ERP_BOLETO
# SET ERP_BOLETO.DM_SITUACAO = 'Quitado'
# WHERE ERP_BOLETO.NR_LICENCA = '24455' AND ERP_BOLETO.GUID_BOLETO = '6a106378-1393-4e08-9aea-673c6d64cd11'

DESC ERP_NUMERACAO_PEDIDO;

