--------------------------------------------------
-- 01. Tabela de clientes
--------------------------------------------------
CREATE TABLE IF NOT EXISTS tb_client (
    customer_id BIGINT NOT NULL,
    enterprise_id INT NOT NULL,
    client_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name varchar(150) NOT NULL,
    last_name varchar(150) NULL,
    cpf_cnpj varchar(14) NOT NULL,
    PRIMARY KEY (customer_id, enterprise_id, client_id),
    CONSTRAINT fk_enterprise_client
        FOREIGN KEY (customer_id, enterprise_id)
            REFERENCES tb_enterprise(customer_id, enterprise_id)
);

--------------------------------------------------
-- 02. Tabela de Fornecedores
--------------------------------------------------
-- CREATE TABLE IF NOT EXISTS tb_supplier (
--     customer_id BIGINT NOT NULL,
--     enterprise_id INT NOT NULL,
--     supplier_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL
-- );